version: 2

references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependency-{{ checksum "package-lock.lock" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependency-

jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: 
          name: install npm dependecies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key
      - run: npm test

  pre_release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: install npm dependecies
          command: npm i
      - run: git config --global push.default current
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"
      - run: npm run release:pre
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: install npm dependecies
          command: npm i
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"
      - run: npm run release
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  pre_docs_deliver:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: npm i
      - run: npm run docs:build
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS docker-registry.darteaga.com
      - run: npm run docs:docker:push
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key
  
  docs_deliver:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: git pull
      - run: npm i
      - run: npm run docs:version
      - run: git config --global push.default current
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"
      - run: git add .
      - run: | 
          git commit -m "docs: fix new docs version [ci skip]"
      - run: git push
      - run: npm run docs:build
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS docker-registry.darteaga.com
      - run: npm run docs:docker:push
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  pre_npm_publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: git pull origin develop
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Build assests
          command: npm run build
      - run:
          name: Publish package
          command: npm publish --tag next dist/
          
  npm_publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: git pull
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Build assests
          command: npm run build
      - run:
          name: Publish package
          command: npm publish dist/
  next:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"
      - run: git pull
      - run: git checkout develop
      - run: |
          git merge master --strategy-option theirs -m "chore: prepare develop for the next iteration [ci skip]"
      - run: git push

workflows:
  version: 2
  all:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - master
                
  canary:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
      - pre_release:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - pre_docs_deliver:
          requires:
            - pre_release
          filters:
            branches:
              only:
                - develop
      - pre_npm_publish:
          requires:
            - pre_docs_deliver
          filters:
            branches:
              only:
                - develop
              
  production:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - docs_deliver:
          requires:
            - release
          filters:
            branches:
              only:
                - master
      - next:
          requires:
            - docs_deliver
          filters:
            branches:
              only:
                - master
      - npm_publish:
          requires:
            - docs_deliver
          filters:
            branches:
              only:
                - master

