version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0
  
references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependency-{{ checksum "package-lock.json" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependency-
    
commands:
  git_authoring:
    description: Authoring git commit.
    steps:
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"
      
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run: 
          name: Install npm dependecies.
          command: npm i
      - run: 
          name: Launch unit tests.
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - git_authoring
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: Bump and publish the new version.
          command: npm run release
  
  docs_deliver:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - git_authoring
      - setup_remote_docker:
          docker_layer_caching: true    
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: Get latest changes from the repository.
          command: git pull
      - run:
          name: Generate a new docs website version.
          command: npm run docs:version
      - run:
          name: Add commit with doc changes.
          command: | 
            git add .
            git commit -m "docs: fix new docs version [ci skip]"
            git push
      - run:
          name: Build docs website assests. 
          command: npm run docs:website
      - run:
          name: Setup hygeia-js version environment variables.
          command: |
            echo 'export HYGEIA_JS_VERSION="$(npm run --silent get:version)"' >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          dockerfile: website/dockerfile
          repo: hygeia/hygeia-docs
          region: AWS_DEFAULT_REGION
          tag: latest,${HYGEIA_JS_VERSION}
          
  npm_publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - *js_deps_cache_key
          - *js_deps_backup_cache_key
      - run:
          name: Get latest changes from the repository.
          command: git pull
      - run:
          name: Authenticate against npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Build hygeia-js assests.
          command: npm run build
      - run:
          name: Publish hygeia-js package to npm.
          command: npm publish dist/

workflows:
  version: 2
  all:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
              
  production:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master

      - docs_deliver:
          requires:
            - release
          filters:
            branches:
              only:
                - master

      - npm_publish:
          requires:
            - docs_deliver
          filters:
            branches:
              only:
                - master

